version: '3'

services:
### NGINX Server #########################################
  nginx:
    build: ./nginx
    env_file:
     - .env
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"

### PHP-FPM ##############################################
  php-fpm:
    build: ./php-fpm
    env_file:
     - .env
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    ports:
      - "${NGINX_PHP_UPSTREAM_PORT}:9000"

### MySQL ################################################
  mysql:
    #phpmyadminのconfig.inc.phpで$hostsがdbに指定されているため使用
    container_name: db
    build: ./mysql
    env_file:
      - .env
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    user: "1000:50"

### phpMyAdmin ###########################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env
    volumes:
      - /sessions
    ports:
      - "${PMA_PORT}:80"
